steps:
  # 1. Evaluación 
  - name: 'python:3.10'
    id: 'Pruebas_de_Calidad'
    dir: 'parallel-agent'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        pip install google-adk
        pip install 'google-adk[eval]'

        echo "Contenido del directorio actual:"
        ls -F
        
        adk eval ./planificador_viajes ./planificador_viajes/planificador_evalset.evalset.json \
          --config_file_path=./planificador_viajes/test_config.json \

  # 2. Despliegue 
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Actualizacion_Agent_Engine'
    dir: 'parallel-agent'
    entrypoint: /bin/bash
    args:
      - -c
      - | 
        cloud beta ai reasoning-engines deploy \
          --project=interno-geminienterprise \
          --location=us-central1 \
          --agent-id="2693689688597725184" \
          --source="." \
          --alias="prod"

options:
  logging: CLOUD_LOGGING_ONLY