steps:
  # 1. Instalación y Evaluación 
  - name: 'python:3.10'
    id: 'Pruebas_de_Calidad'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        # Instalamos las herramientas necesarias en este contenedor
        pip install google-adk
        pip install 'google-adk[eval]'
        
        # Ejecutamos la evaluación inmediatamente
        adk eval planificador_viajes planificador_viajes/planificador_evalset.evalset.json \
          --config_file_path=planificador_viajes/test_config.json \
          --print_detailed_results

  # 2. Despliegue 
  - name: 'python:3.10'
    id: 'Despliegue_Agent_Engine'
    entrypoint: /bin/bash
    args:
      - -c
      - |
        pip install google-adk
        adk deploy agent_engine \
          --project=interno-geminienterprise \
          --region=us-central1 \
          planificador_viajes

options:
  logging: CLOUD_LOGGING_ONLY